language: node_js

git:
  depth: 9999999

notifications:
  slack:
    secure: GGEj/Le86q43uut1t80489nQrhgumXpB9TtYjsiXJpqnljU5TM39EEPWUOR6/a3+UMmKbEIoupm0bBQqokeEc4PE/aXIL5RVCWzdRNVP1kvqMi1giKtqhj3ni3cyRSALmSjYNNQdsBrpbUMdbSfoR3nqNNcLIkmJUNkzSeevVQztyWJQGQ0dNu3Uf4B9BAwuoeexP/9UZlmC5kw0abVukD3tYiH0xHkwjmkhPNHlrOQFW9u8Id6uhTqUOouGQlIzD7yJgyE8joTUO0XaGwWVD3pbBkr/amG0ARzt/Cn5bGuiAMG70JRNL/FGopcX+7YlCS75DqCgNwvk9dmWa/d/hiOuLNGrLKbYb3sDgbMHYM+jyb7pqZptvsUH3nkZJQK+5cEhaixx56v6PZnvHlonpneHukqYb+X6BKKFYYgLH/ZdA14ywF4ch3GJWv2Oo4dIsR1vLc19n6ZIVzaZqjMPKZo//bsOA5HMh/hQSoRL8fWDTvftQiUCDhmk9I0CWJ/cfspORqjIMARg8da4YkIIRs70yAak5kr1/A0WzaQVXopema7K5PEvCbqnUz8AVU7OUdZmjoujX05yI8+4GhVtct6n32w8MIV9wbBY9qjpoQIaH9BbWVRl7+uKvBwLeWhxeyV5Gay8hn68TqgTtV/eQwA5SrBwa6cAbS+l9FaZHx8=

node_js:
- iojs-v2.4.0

deploy:
  provider: npm
  email: jeff.panici@panici-software.com
  api_key:
    secure: j9P5vDGF5RzQQjsHri1F4l5MGQjPvacrdXjIfk83qakb1NVtNyJdboIv+xVW9sGGlRhzVbWQk7MDw5yvKe0y8xjzfZue4k6RswMWRbOI/lDAVW+CdugTF6assqAukG4M3pes1hKODJOkXlaYkYmmGWETrhZXSjzPVWmZgQy8oEJbZnZXaKtdQSGnQujzEwPcDjm695uRlLUtjC/nRyja0Y3MjQOePxTn2FksWzWq249g0HhSHY7kGl2jbxe9Ih7PulYYJL5Vwqp+Xcc2KyYv+XHw2SSSok3VxOshSoux+0AwA0W8r5cjW0bFrJTpOLcjjcwYTxqGaTpiW6+6gdlekoNp2Hw1mStO/nUUPM580QrU1XG/RvPbvjvtZM39AoYWlhdu798cbjth3t3aBcOlCsYjj44tM9xx5CPL4Pbn1mDQrNH4LzHQ+5OcuIUFEhQnPSl7PtMe6enDXnC4jjLct3T5GWkVv0G0erPBik1tWtHWwnm6uPkAA8YbM6NtLWYQSwSU4FDz26YutCA1R4xAds62iV8NvMcw0cQKuDj+4KZHGOLSy3FeDngh0KN3MFcB9oAjsr/B1GIRqPJplT2LWoGUws/iY0zJbmVyq5FGoUuaZfw3LLgHelO3+3R1P1YH6BPUkdJtzvNQQttRjvCWnGpDO0kVfpXBQ5bHf5wZeFY=
  on:
    tags: true
