language: node_js

git:
  depth: 9999999

notifications:
  slack:
    secure: GGEj/Le86q43uut1t80489nQrhgumXpB9TtYjsiXJpqnljU5TM39EEPWUOR6/a3+UMmKbEIoupm0bBQqokeEc4PE/aXIL5RVCWzdRNVP1kvqMi1giKtqhj3ni3cyRSALmSjYNNQdsBrpbUMdbSfoR3nqNNcLIkmJUNkzSeevVQztyWJQGQ0dNu3Uf4B9BAwuoeexP/9UZlmC5kw0abVukD3tYiH0xHkwjmkhPNHlrOQFW9u8Id6uhTqUOouGQlIzD7yJgyE8joTUO0XaGwWVD3pbBkr/amG0ARzt/Cn5bGuiAMG70JRNL/FGopcX+7YlCS75DqCgNwvk9dmWa/d/hiOuLNGrLKbYb3sDgbMHYM+jyb7pqZptvsUH3nkZJQK+5cEhaixx56v6PZnvHlonpneHukqYb+X6BKKFYYgLH/ZdA14ywF4ch3GJWv2Oo4dIsR1vLc19n6ZIVzaZqjMPKZo//bsOA5HMh/hQSoRL8fWDTvftQiUCDhmk9I0CWJ/cfspORqjIMARg8da4YkIIRs70yAak5kr1/A0WzaQVXopema7K5PEvCbqnUz8AVU7OUdZmjoujX05yI8+4GhVtct6n32w8MIV9wbBY9qjpoQIaH9BbWVRl7+uKvBwLeWhxeyV5Gay8hn68TqgTtV/eQwA5SrBwa6cAbS+l9FaZHx8=

node_js:
- iojs-v2.4.0

deploy:
  provider: npm
  email: jeff.panici@panici-software.com
  api_key:
    secure: ICmu0s/t+JTft9/bTcSKJ232NAI3rdOZVKS1WQEKyTD1hlJDZu3Ik2HSXKHhM4RQPEJEv1OoEdhrITddeHSjpD7YWF39uXm2siigLwhZvicNd4LV3I4yTd1ExoN3XIqZKF3Wtzp2sL0qZDG3o82tpIKgUjQ7IuIWu27z5BbnIMU9emKqlwAlBRUQv1Ya2CBkvwsmeh5IrhSeF8YJnipfcR7Ckp47Mg1FcxsmtqoaU7IOoBvy/68J/ZFd3y1hGQnJ7ELTeI899mu5tOl9KOLj/DFPIEPupa5Rl4qdkeUcpt2BxSMgye4vwYIpoW08B4E0HkgN+xitgt9kpKska75JJ1TRAiKDfBD3nhdCQq3T7YwdPkkprtCzfCY14yS2dCWTmCwV3ARNkhzvXrKyYLBvnjojvR8GDY9ZXJ4Tr+6jyg1IyArs0+Yrlek2KAOg2NrpvIKdmLPC/K9kZwFrhXKMhPYjjy6nboGx3prpfh1O/g7/KVJxRRN9BVYulu+bGyMKXM1/j+eNKGv5uNhC/19aqy8pdJpt+RGBrMmslnzS+yU5QwH84JfoKL5D3o/ZOx+LKyhhe6P6VvODH87/puV7BMq9stDOmbZpq8OLJZnl3QjJItsD9U2XUGeRZcAUns0WPR/I9LL+Bg/pl1nb83em8T1YduCBctH+6gzC080/25w=
  on:
    tags: true
