language: node_js
git:
  depth: 9999999
notifications:
  slack:
    secure: GGEj/Le86q43uut1t80489nQrhgumXpB9TtYjsiXJpqnljU5TM39EEPWUOR6/a3+UMmKbEIoupm0bBQqokeEc4PE/aXIL5RVCWzdRNVP1kvqMi1giKtqhj3ni3cyRSALmSjYNNQdsBrpbUMdbSfoR3nqNNcLIkmJUNkzSeevVQztyWJQGQ0dNu3Uf4B9BAwuoeexP/9UZlmC5kw0abVukD3tYiH0xHkwjmkhPNHlrOQFW9u8Id6uhTqUOouGQlIzD7yJgyE8joTUO0XaGwWVD3pbBkr/amG0ARzt/Cn5bGuiAMG70JRNL/FGopcX+7YlCS75DqCgNwvk9dmWa/d/hiOuLNGrLKbYb3sDgbMHYM+jyb7pqZptvsUH3nkZJQK+5cEhaixx56v6PZnvHlonpneHukqYb+X6BKKFYYgLH/ZdA14ywF4ch3GJWv2Oo4dIsR1vLc19n6ZIVzaZqjMPKZo//bsOA5HMh/hQSoRL8fWDTvftQiUCDhmk9I0CWJ/cfspORqjIMARg8da4YkIIRs70yAak5kr1/A0WzaQVXopema7K5PEvCbqnUz8AVU7OUdZmjoujX05yI8+4GhVtct6n32w8MIV9wbBY9qjpoQIaH9BbWVRl7+uKvBwLeWhxeyV5Gay8hn68TqgTtV/eQwA5SrBwa6cAbS+l9FaZHx8=
node_js:
- iojs-v2.3.1
deploy:
  provider: npm
  email: jeff.panici@panici-software.com
  api_key:
    secure: Vxz+ECm3Q89ah/KROx119u8C05xcywxdDJtbIrv85qffaW37+hb60uY++aOO7HXPCC6hfXvrsGzG5XxVxlY8dNj8fW+lVaidUmkcwYgD0136WIsypI80FTaGJt2A12H6k62K8AqTJrSkHGwy/eSytgfJH5457xIrwlB+fKyGILbDXCFn8eMxnfL4f95IzuWXTcnX2zu5kfywMuuO7mxR6lI07A8DdQDhYakYlcgsffsxUUxkdWl0Uady+9JD6kVygtEKmXbjLoQZT2BqrJEupVp3rM1wNamaBFr0GKSqporGa/WA5Bo1om7XS/JvqNNokPXpw7/HyNONdnE25agLN2j7lKRCKybI6Eb3h2HUiSHpQGoNkPG09cnemzHX3+Ac30o045rrjiD3i0dJD7tFiNp3kfoC+sNIOjlzFieRfoRQtXMXXAa0B/1b2kb22mnlfEdA5KvdZNDPxD/IhzHg0vkntHi/3unsLiFI0OfryeCV8LHSuxRJ0iaoqmdb+IgK7/AklBCZ6Uc4i2Rt8Ec5/3v3EjqqnEwu4NgpIq1/KoiXvCSJq87/+Ly5Tcn0jQi7LOlNTMtgCr4aHY2mfw5KqAmec4S4tu+wALxUg0BQgVY4mTi3tJX7+Iy8ZMObWdH9qKpALa1pUc5lv6EukPxs0NIeqMrgjhQK5NXXePld8Jk=
  on:
    tags: true
