language: node_js
git:
  depth: 9999999
notifications:
  slack:
    secure: YSfSuoYkDsUd/R5XRyz+dEASITvP+BmGZaN2V8/EHBaXMsMG0iOmH3G07YSqRIt3Wch76kkHwwp+TLOMN5tvxIW4o5MNE0vCcg5T5oGm766zVUYVIaordUmN+lvr2lc7HGKCDOQECV2kvLdCUCQiaaUKu3Dhi0dy5uCJ9sUG7GLlk2iRCrc2idYpXe6/jE+osX2LGcUNfscmVdSh9MicnyY16HRlNGCqnpAxAlzM20sXfgo8i1u8kLdCFNGcjS0eUgy1y6Jfnp3x2X3InRuiKL88LqFOYUdvVHZ/Eu5XB0jdsAbEqWaTyOz9aUGsnpcP701Jw+lCAaeZaSSGag5J6glht9JAhKGHE9H2uoIQ/GMvB42Ns7H4bM7d4YORnUXJtZVpC3vaLLN+PxgobcrNA5b7o09v+7cuiyN7/Utl63l+PyVTcSv4qWc9nGWzVOBmgwKpV1sxUrSEiJaZ1gr4ysPNjCDzyJz3z7PWZYhzHkS2qozaP5KfJu335NybBtLbU0/q/6oky7beciCyc8KqWSryl/71TaT29ls0vFIOYwKE6N8k/ztWWBM38h++g9d0dis8TB2Qu8aWmc1rtmwdO059ufdvoMv6451ugGjMDE6Swub8z8T97OfBT1z7wodnOjH91WWFjCdku9Wb9HSBL4RXcp43KZHnWJSBbsTvgjg=
node_js:
- iojs-v2.3.1
deploy:
  provider: npm
  email: jeff.panici@panici-software.com
  api_key:
    secure: WodUieSN9Uw75D+nooXDpSH95CbuF0wUjoZh4ww2FB9oeetv0Q1oIeFM3A45qITowerl3m3l3ueXU8M17Q8vXNvoOxh7ixxCOj2oveKpXfY5x5y+7xO0KS5YESGJnODWO9e3gD6XXce6Ol1/6+UBzBocKka/xBETV1WvpDgwe4W1L/LX2ncIYjD6IYQ/FT/iGp0T/MO6VmSA3xJqa45WxwiatT6gFXHdTayQpbktvXZW7rSnUqbAqt5JITx2qqmexiFZVQEsAU3Cgg/PaQufGtrkcgrACVx6L/ApLQT+00f+SKQugPo6Ci17YuSUIJJCsBmeOQcP7vCs+9UVaY6P5DWR1Rwkxv9u50W4X0rcDz6XVlGu2CuvmWwEk1zPg/1XtTj6hQnNo81F0ONvbPsb/7i0DVPCxsKPwXGb+KyNNAElK4xAa/1qrP1gdHjMJ4fu3JrjE+MdNX4f9WHRWoqH4mc733k/yb3flWSeFWM59eJZjRxmJJLFFVDYpvFlX7ZXgQ/0Y71GM3U+gG+e4qZlITVtNtw5kkDAjTmUw4vNpL1NQKXi3tHqIvlHn/h9YdeYklw/smYEF2hCxD1f2w+/xTUqzNAzAE7skOy3j1gldI5Rw0JzeGBVvP+T0/kZsHZixveB5jgLjfUWHfM2BFl77ngQRd2WpAfXZNIp0YIOYl4=
  on:
    tags: true
